-- funciones en haskell
-- head: Retorna el primer elemento de la lista.
-- last: Retorna el último elemento de la lista.
-- tail: Retorna todos los elementos menos el primero.
-- init: Retorna todos los elementos menos el último.
-- length: Retorna el número de elementos de la lista.
-- take: Retorna los primeros n elementos de la lista.
-- drop: Retorna los elementos de la lista, excepto los n primeros.
-- takeWhile : Más potente que take pues puede retornar ciertos tipos de datos indicados.
-- dropWhile: Más potente que drop pues puede retornar ciertos tipos de datos indicados.
-- reverse: Invierte una lista.
-- concat: Toma ciertos elementos o listas y las retorna en una sola lista.
-- words: Retorna una lista de strings de acuerdo a los espacios en blanco de un string.
-- unwords: Retorna un string de una lista de strings.
-- elem: Retorna si un elemento esta o no en la lista
-- notElem: Lo opuesto a elem.